auction:
  products:
    - name: "Tulip Bouquet"
      description: "Premium Dutch tulips, freshly cut."
      starting_price: 200.0
      min_price: 50.0
      price_step: 5.0
      tick_seconds: 1.5
      retail_demand_index: 0.7
      wholesale_colors: ["red", "yellow", "white", "pink", "purple"]
    - name: "Orchid Box"
      description: "Exotic orchids, limited edition."
      starting_price: 350.0
      min_price: 120.0
      price_step: 10.0
      tick_seconds: 2.0
      retail_demand_index: 0.4
      wholesale_colors: ["white", "purple"]
  human_player_id: "human"
  auto_reset: true
  reset_delay_seconds: 4.0
players:
  - id: "p1"
    name: "Amstel Florist"
    balance: 600.0
    preferred_colors: ["red","yellow"]
    strategy: "threshold"
    threshold: 150.0
  - id: "p2"
    name: "Canal Blooms"
    balance: 300.0
    preferred_colors: ["white"]
    strategy: "patient"
    threshold: 140.0
    patience_factor: 0.85
  - id: "p3"
    name: "Keukenhof Co"
    balance: 450.0
    preferred_colors: ["pink","purple"]
    strategy: "demand_aware"
    base_threshold: 160.0
  - id: "p4"
    name: "Windmill Flowers"
    balance: 220.0
    preferred_colors: ["yellow"]
    strategy: "randomized"
    soft_threshold: 170.0
    buy_chance: 0.35
  - id: "p5"
    name: "Harbor Petals"
    balance: 520.0
    preferred_colors: ["red","white"]
    strategy: "budget_guard"
    threshold: 155.0
    reserve: 80.0
  - id: "p6"
    name: "Night Market"
    balance: 180.0
    preferred_colors: ["purple"]
    strategy: "sniper"
    trigger_price: 120.0
